export const services =  {
    categories: ['All', 'Beginner', 'Intermediate', 'Expert'],
    packages: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'Sierra Bowl', category: 'Intermediate', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/Services/service-2.jpg', title: 'Raspberry Mug', category: 'Beginner', description: 'A description of our service...', cost: 15000 },
        { id: 3, image: '/assets/img/Services/service-3.jpg', title: 'Petal Plate', category: 'Expert', description: 'A description of our service...', cost: 5000 },
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Beret Bowl', category: 'Beginner', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/Services/service-5.jpg', title: 'Lava Rock Vase', category: 'Intermediate', description: 'A description of our service...', cost: 7500 },
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Petal Vase ', category: 'Expert', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/Services/service-7.jpg', title: 'Desert Vase', category: 'Beginner', description: 'A description of our service...', cost: 8000 },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'Square Bowl', category: 'Intermediate', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/Services/service-9.jpg', title: 'Ring Vase', category: 'Expert', description: 'A description of our service...', cost: 7000 },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: 'Oatmeal Bowl', category: 'Beginner', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Lavender Bowl', category: 'Beginner', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/Services/service-12.jpg', title: 'Fish Soap Tray', category: 'Expert', description: 'A description of our service...', cost: 9000 },
        { id: 13, image: '/assets/img/Services/service-13.jpg', title: 'Share Bowl', category: 'Beginner', description: 'A description of our service...', cost: 9000 },
        { id: 14, image: '/assets/img/Services/service-14.jpg', title: 'Bud Vase', category: 'Intermediate', description: 'A description of our service...', cost: 9000 },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Flower Bowl', category: 'Intermediate', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Snack Bowl', category: 'Intermediate', description: 'A description of our service...', cost: 9000 },
    ],
}